// frontend/src/lib/components/ui/button-link.svelte
<script lang="ts" module>
	export interface ButtonLinkProps
		extends HTMLAnchorAttributes,
			VariantProps<typeof buttonVariants> {}
</script>

<script lang="ts">
	import { buttonVariants } from './button.svelte';
	import type { VariantProps } from 'class-variance-authority';
	import type { HTMLAnchorAttributes } from 'svelte/elements';

	import { cn } from '$lib/utils';

	let {
		class: className = '',
		variant,
		size,
		children,
		...rest
	}: ButtonLinkProps = $props();
</script>

<a
	{...rest}
	class={cn(buttonVariants({ variant: variant, size: size, className }))}
>
	{@render children?.()}
</a>

// frontend/src/lib/components/ui/button-link.tsx
import { buttonVariants } from './button';
import { A } from '@solidjs/router';
import { type VariantProps } from 'class-variance-authority';
import { splitProps, type ComponentProps } from 'solid-js';

export type ButtonLinkProps = ComponentProps<typeof A> & VariantProps<typeof buttonVariants>;

export function ButtonLink(props: ButtonLinkProps) {
	const [local, rest] = splitProps(props, ['class', 'classList', 'variant', 'size', 'children']);

	return (
		<A
			{...rest}
			class={buttonVariants({
				variant: local.variant,
				size: local.size,
				class: local.class
			})}
			classList={local.classList}
		>
			{local.children}
		</A>
	);
}
