// frontend/src/lib/components/ui/input.tsx
import { cn } from '@/lib/utils';
import { splitProps } from 'solid-js';
import type { JSX } from 'solid-js/h/jsx-runtime';

export type InputProps = JSX.InputHTMLAttributes<HTMLInputElement>;

export function Input(props: InputProps) {
	const [local, rest] = splitProps(props, ['class']);

	return (
		//@ts-ignore
		<input
			class={cn(
				'w-full rounded border bg-muted px-4 py-2 ring-primary outline-none focus-visible:ring',
				local.class
			)}
			{...rest}
		/>
	);
}

// frontend/src/lib/components/ui/input.svelte
<script lang="ts" module>
	export interface InputProps extends HTMLInputAttributes {}
</script>

<script lang="ts">
	import type { HTMLInputAttributes } from 'svelte/elements';

	import { cn } from '$lib/utils';

	let {
		class: className = '',
		value = $bindable(),
		...rest
	}: InputProps = $props();
</script>

<input
	{...rest}
	bind:value
	class={cn(
		'bg-muted ring-primary rounded border px-4 py-2 outline-none focus-visible:ring',
		className
	)}
/>
